=== piaolingxue/demo/docbook/form-sampler/form-sampler.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="http://www.xmlmind.com/xmleditor/schema/form-sampler"
    xmlns="http://www.xmlmind.com/xmleditor/schema/form-sampler" 
    elementFormDefault="qualified">

<xs:element name="doc">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="para" type="Para" 
                  minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="Para" mixed="true">
  <xs:group ref="Mix" minOccurs="0" maxOccurs="unbounded" />
</xs:complexType>

<xs:group name="Mix">
  <xs:choice>
    <xs:element name="bold" type="Bold" />
    <xs:element name="onoff" type="OnOff" />
    <xs:element name="yesno" type="YesNo" default="no" />
    <xs:element name="disabled" type="Disabled" />
    <xs:element name="hidden" type="Hidden" />
    <xs:element name="rgb1" type="RGB1" />
    <xs:element name="rgb2" type="RGB" default="blue" />
    <xs:element name="integer1" type="Integer" />
    <xs:element name="integer2" type="xs:int" default="0" />
    <xs:element name="uri1" type="URI" />
    <xs:element name="uri2" type="xs:anyURI" default="form-sampler.xml" />
    <xs:element name="fileName" type="xs:string" default="form-sampler.xml" />
    <xs:element name="cymk1" type="CYMK1" />
    <xs:element name="cymk2" type="CYMK" default="black" />
    <xs:element name="cymklist1" type="ListOfCYMK1" />
    <xs:element name="cymklist2" type="ListOfCYMK" default="black" />
    <xs:element name="cymka" type="CYMK1" />
    <xs:element name="cymkb" type="CYMK" default="black" />
    <xs:element name="cymklista" type="ListOfCYMK1" />
    <xs:element name="cymklistb" type="ListOfCYMK" default="black" />
    <xs:element name="string1" type="String" />
    <xs:element name="string2" type="xs:string" />
    <xs:element name="date1" type="Date" />
    <xs:element name="date2" type="xs:date" default="1960-03-16" />
    <xs:element name="time1" type="Time" />
    <xs:element name="time2" type="xs:time" default="13:15:05.10" />
    <xs:element name="dateTime1" type="DateTime" />
    <xs:element name="dateTime2" type="xs:dateTime" 
                default="1960-03-16T13:15:05Z" />
    <xs:element name="day1" type="Day" />
    <xs:element name="day2" type="xs:gDay" default="---16" />
    <xs:element name="monthDay1" type="MonthDay" />
    <xs:element name="monthDay2" type="xs:gMonthDay" default="--03-16" />
    <xs:element name="month1" type="Month" />
    <xs:element name="month2" type="xs:gMonth" default="--03" />
    <xs:element name="yearMonth1" type="YearMonth" />
    <xs:element name="yearMonth2" type="xs:gYearMonth" default="1960-03" />
    <xs:element name="year1" type="Year" />
    <xs:element name="year2" type="xs:gYear" default="1960" />
    <xs:element name="byte1" type="Byte" />
    <xs:element name="byte2" type="xs:byte" default="127" />
    <xs:element name="short1" type="Short" />
    <xs:element name="short2" type="xs:short" default="32767" />
    <xs:element name="int1" type="Int" />
    <xs:element name="int2" type="xs:int" default="2147483647" />
    <xs:element name="long1" type="Long" />
    <xs:element name="long2" type="xs:long" default="9223372036854775807" />
    <xs:element name="float1" type="Float" />
    <xs:element name="float2" type="xs:float" default="2.7182817" />
    <xs:element name="double1" type="Double" />
    <xs:element name="double2" type="xs:double" default="2.718281828459045" />

    <xs:element name="byteA" type="ByteType" />
    <xs:element name="byteE" type="xs:byte" default="0" />
    <xs:element name="shortA" type="ShortType" />
    <xs:element name="shortE" type="xs:short" default="0" />
    <xs:element name="intA" type="IntType" />
    <xs:element name="intE" type="xs:int" default="0" />
    <xs:element name="longA" type="LongType" />
    <xs:element name="longE" type="xs:long" default="0" />
    <xs:element name="floatA" type="FloatType" />
    <xs:element name="floatE" type="xs:float" default="0" />
    <xs:element name="doubleA" type="DoubleType" />
    <xs:element name="doubleE" type="xs:double" default="0" />

    <xs:element name="date30" type="Date" />
    <xs:element name="date40" type="xs:date" default="1960-03-16" />

    <xs:element name="date31" type="Date31" />
    <xs:element name="date41" type="Date41" default="03/16/1960" />

    <xs:element name="time30" type="Time" />
    <xs:element name="time40" type="xs:time" default="13:15:05.10" />

    <xs:element name="time31" type="Time31" />
    <xs:element name="time41" type="Time41" default="1315" />

    <xs:element name="dateTime30" type="DateTime" />
    <xs:element name="dateTime40" type="xs:dateTime" 
                default="1960-03-16T13:15:05Z" />

    <xs:element name="dateTime31" type="DateTime31" />
    <xs:element name="dateTime41" type="DateTime41"
                default="1315 03/16/1960" />

    <xs:element name="dateTime32" type="DateTime32" />
    <xs:element name="dateTime42" type="xs:double" default="0" />

    <xs:element name="dateTime33" type="DateTime33" />
    <xs:element name="dateTime43" type="xs:long" default="0" />
  </xs:choice>
</xs:group>

<xs:complexType name="Bold" mixed="true">
  <xs:group ref="Mix" minOccurs="0" maxOccurs="unbounded" />
</xs:complexType>

<xs:complexType name="OnOff">
  <xs:attribute name="value" type="xs:boolean" default="false" />
</xs:complexType>

<xs:simpleType name="YesNo">
  <xs:restriction base="xs:NMTOKEN">
    <xs:enumeration value="no" />
    <xs:enumeration value="yes" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="Disabled">
  <xs:attribute name="value">
    <xs:simpleType>
      <xs:restriction base="xs:NMTOKEN">
	<xs:enumeration value="disabled" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
</xs:complexType>

<xs:complexType name="Hidden" mixed="true">
</xs:complexType>

<xs:simpleType name="RGB">
  <xs:restriction base="xs:NMTOKEN">
    <xs:enumeration value="red" />
    <xs:enumeration value="green" />
    <xs:enumeration value="blue" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="RGB1">
  <xs:attribute name="value" type="RGB" default="blue" />
</xs:complexType>

<xs:complexType name="Integer">
  <xs:attribute name="value" type="xs:int" default="0" />
</xs:complexType>

<xs:complexType name="URI">
  <xs:attribute name="value" type="xs:anyURI" default="form-sampler.xml" />
</xs:complexType>

<xs:simpleType name="CYMK">
  <xs:restriction base="xs:NMTOKEN">
    <xs:enumeration value="cyan" />
    <xs:enumeration value="yellow" />
    <xs:enumeration value="magenta" />
    <xs:enumeration value="black" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="CYMK1">
  <xs:attribute name="value" type="CYMK" default="black" />
</xs:complexType>

<xs:complexType name="ListOfCYMK1">
  <xs:attribute name="value" default="black">
    <xs:simpleType>
      <xs:restriction base="xs:string">
	<xs:pattern value="((cyan)|(yellow)|(magenta)|(black))(,((cyan)|(yellow)|(magenta)|(black)))?" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
</xs:complexType>

<xs:simpleType name="ListOfCYMK">
  <xs:list itemType="CYMK" />
</xs:simpleType>

<xs:complexType name="String">
  <xs:attribute name="value" type="xs:string" />
  <xs:attribute name="rows" type="xs:positiveInteger" />
  <xs:attribute name="columns" type="xs:positiveInteger" />
</xs:complexType>

<xs:complexType name="Date">
  <xs:attribute name="value" type="xs:date" default="1960-03-16" />
</xs:complexType>

<xs:complexType name="Time">
  <xs:attribute name="value" type="xs:time" default="13:15:05.10" />
</xs:complexType>

<xs:complexType name="DateTime">
  <xs:attribute name="value" type="xs:dateTime" 
                default="1960-03-16T13:15:05Z" />
</xs:complexType>

<xs:complexType name="Day">
  <xs:attribute name="value" type="xs:gDay" default="---16" />
</xs:complexType>

<xs:complexType name="MonthDay">
  <xs:attribute name="value" type="xs:gMonthDay" default="--03-16" />
</xs:complexType>

<xs:complexType name="Month">
  <xs:attribute name="value" type="xs:gMonth" default="--03" />
</xs:complexType>

<xs:complexType name="YearMonth">
  <xs:attribute name="value" type="xs:gYearMonth" default="1960-03" />
</xs:complexType>

<xs:complexType name="Year">
  <xs:attribute name="value" type="xs:gYear" default="1960" />
</xs:complexType>

<xs:complexType name="Byte">
  <xs:attribute name="value" type="xs:byte" default="-128" />
</xs:complexType>

<xs:complexType name="Short">
  <xs:attribute name="value" type="xs:short" default="-32768" />
</xs:complexType>

<xs:complexType name="Int">
  <xs:attribute name="value" type="xs:int" default="-2147483648" />
</xs:complexType>

<xs:complexType name="Long">
  <xs:attribute name="value" type="xs:long" default="-9223372036854775808" />
</xs:complexType>

<xs:complexType name="Float">
  <xs:attribute name="value" type="xs:float" default="-3.1415927" />
</xs:complexType>

<xs:complexType name="Double">
  <xs:attribute name="value" type="xs:double" default="-3.141592653589793" />
</xs:complexType>

<xs:complexType name="ByteType">
  <xs:attribute name="value" type="xs:byte" default="0" />
</xs:complexType>

<xs:complexType name="ShortType">
  <xs:attribute name="value" type="xs:short" default="0" />
</xs:complexType>

<xs:complexType name="IntType">
  <xs:attribute name="value" type="xs:int" default="0" />
</xs:complexType>

<xs:complexType name="LongType">
  <xs:attribute name="value" type="xs:long" default="0" />
</xs:complexType>

<xs:complexType name="FloatType">
  <xs:attribute name="value" type="xs:float" default="0" />
</xs:complexType>

<xs:complexType name="DoubleType">
  <xs:attribute name="value" type="xs:double" default="0" />
</xs:complexType>

<xs:complexType name="Date31">
  <xs:attribute name="value" type="Date41" default="03/16/1960" />
</xs:complexType>

<xs:simpleType name="Date41">
  <xs:restriction base="xs:token">
    <xs:pattern value="\d\d/\d\d/\d\d\d\d" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="Time31">
  <xs:attribute name="value" type="Time41" default="1315" />
</xs:complexType>

<xs:simpleType name="Time41">
  <xs:restriction base="xs:token">
    <xs:pattern value="\d\d\d\d" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="DateTime31">
  <xs:attribute name="value" type="DateTime41" default="1315 03/16/1960" />
</xs:complexType>

<xs:simpleType name="DateTime41">
  <xs:restriction base="xs:token">
    <xs:pattern value="\d\d\d\d \d\d/\d\d/\d\d\d\d" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="DateTime32">
  <xs:attribute name="value" type="xs:double" default="0" />
</xs:complexType>

<xs:complexType name="DateTime33">
  <xs:attribute name="value" type="xs:long" default="0" />
</xs:complexType>

</xs:schema>

=== piaolingxue/demo/docbook/form-sampler.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/css" href="form-sampler/form-sampler.css" 
title="Stylesheet using combo-box(), check-box(), text-field(), etc" ?>
<?xml-stylesheet type="text/css" href="form-sampler/form-sampler2.css" 
alternate="yes" title="Stylesheet exclusively using value-editor()" ?>
<doc xsi:schemaLocation="http://www.xmlmind.com/xmleditor/schema/form-sampler form-sampler/form-sampler.xsd"
     xmlns="http://www.xmlmind.com/xmleditor/schema/form-sampler"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns:ns="http://www.xmlmind.com/xmleditor/schema/form-sampler">
  <para>This demonstration document does not use a XXE configuration to
  specify its style sheet. Instead, it directly references form-sampler.css
  using a &lt;?xml-stylesheet?&gt; processing instruction. Therefore if you
  want to see this document properly styled, do not turn on option
  "<bold>Ignore &lt;?xml-stylesheet?&gt;</bold>"
  (<bold>Options</bold>|<bold>Preferences</bold>, <bold>Open</bold>
  section).</para>

  <para><bold>Check box</bold> used to edit a boolean attribute:
  <onoff /></para>

  <para><bold>Check box</bold> used to edit an element with a yes/no value:
  <yesno></yesno></para>

  <para><bold>Check box</bold> used to add/remove a value to an attribute:
  <disabled value="disabled" /></para>

  <para><bold>Check box</bold> used to add/remove a value to an element:
  <hidden>hidden</hidden></para>

  <para><bold>Combo box</bold> used to edit an attribute specifying
  red/green/blue: <rgb1 /></para>

  <para><bold>Combo box</bold> used to edit an element specifying
  red/green/blue: <rgb2></rgb2></para>

  <para><bold>Text field</bold> used to edit an attribute specifying a 32-bit
  signed integer: <integer1 /></para>

  <para><bold>Text field</bold> used to edit an element specifying a 32-bit
  signed integer: <integer2></integer2></para>

  <para><bold>File name field</bold> used to edit an attribute specifying the
  relative URL of an open file: <uri1 /></para>

  <para><bold>File name field</bold> used to edit an element specifying the
  absolute URL of a save directory: <uri2></uri2></para>

  <para><bold>File name field</bold> used to edit an element specifying the
  absolute path of a save directory: <fileName></fileName></para>

  <para><bold>Text area</bold> used to edit an attribute containing a free
  form string: <string1 columns="60" rows="6" /></para>

  <para><bold>Text area</bold> used to edit an element containing a free form
  string: <string2></string2></para>

  <para>Single selection <bold>list</bold> used to edit an attribute
  specifying cyan/yellow/magenta/black: <cymk1 value="yellow" /></para>

  <para>Single selection <bold>list</bold> used to edit an element specifying
  cyan/yellow/magenta/black: <cymk2>yellow</cymk2></para>

  <para>Multiple selection <bold>list</bold> used to edit an attribute
  specifying 1 or 2 colors separated by a comma, where allowed colors are
  cyan/yellow/magenta/black: <cymklist1 /></para>

  <para>Multiple selection <bold>list</bold> used to edit an element
  specifying 0 to 4 colors, where allowed colors are
  cyan/yellow/magenta/black: <cymklist2></cymklist2></para>

  <para>Single selection <bold>radio button panel</bold> used to edit an
  attribute specifying cyan/yellow/magenta/black: <cymka /></para>

  <para>Single selection <bold>radio button panel</bold> used to edit an
  element specifying cyan/yellow/magenta/black: <cymkb></cymkb></para>

  <para>Multiple selection <bold>check box panel</bold> used to edit an
  attribute specifying 1 or 2 colors separated by a comma, where allowed
  colors are cyan/yellow/magenta/black: <cymklista /></para>

  <para>Multiple selection <bold>check box panel</bold> used to edit an
  element specifying 0 to 4 colors, where allowed colors are
  cyan/yellow/magenta/black: <cymklistb></cymklistb></para>

  <para><bold>Localized fields (en_US)</bold></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a date:
  <date1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a date:
  <date2></date2></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a time:
  <time1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a time:
  <time2></time2></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a date
  and a time: <dateTime1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a date and
  a time: <dateTime2></dateTime2></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a day:
  <day1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a day:
  <day2></day2></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a
  month/day: <monthDay1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a
  month/day: <monthDay2></monthDay2></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a month:
  <month1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a month:
  <month2></month2></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a
  year/month: <yearMonth1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a
  year/month: <yearMonth2></yearMonth2></para>

  <para><bold>Date field</bold> used to edit an attribute specifying a year:
  <year1 /></para>

  <para><bold>Date field</bold> used to edit an element specifying a year:
  <year2></year2></para>

  <para><bold>Number field</bold> used to edit an attribute specifying a byte:
  <byte1 /></para>

  <para><bold>Number field</bold> used to edit an element specifying a byte:
  <byte2></byte2></para>

  <para><bold>Number field</bold> used to edit an attribute specifying a
  short: <short1 /></para>

  <para><bold>Number field</bold> used to edit an element specifying a short:
  <short2></short2></para>

  <para><bold>Number field</bold> used to edit an attribute specifying a int:
  <int1 /></para>

  <para><bold>Number field</bold> used to edit an element specifying a int:
  <int2></int2></para>

  <para><bold>Number field</bold> used to edit an attribute specifying a long:
  <long1 /></para>

  <para><bold>Number field</bold> used to edit an element specifying a long:
  <long2></long2></para>

  <para><bold>Number field</bold> used to edit an attribute specifying a
  float: <float1 /></para>

  <para><bold>Number field</bold> used to edit an element specifying a float:
  <float2></float2></para>

  <para><bold>Number field</bold> used to edit an attribute specifying a
  double: <double1 /></para>

  <para><bold>Number field</bold> used to edit an element specifying a double:
  <double2></double2></para>

  <para><bold>Spinner</bold> used to edit an attribute specifying a byte:
  <byteA /></para>

  <para><bold>Spinner</bold> used to edit an element specifying a byte
  (step=2): <byteE></byteE></para>

  <para><bold>Spinner</bold> used to edit an attribute specifying a
  short (en_US, min=0): <shortA /></para>

  <para><bold>Spinner</bold> used to edit an element specifying a short
  (en_US, max=0): <shortE></shortE></para>

  <para><bold>Spinner</bold> used to edit an attribute specifying a int
  (en_US, min=0, max=100, step=10): <intA /></para>

  <para><bold>Spinner</bold> used to edit an element specifying a int
  (en_US, columns=5): <intE></intE></para>

  <para><bold>Spinner</bold> used to edit an attribute specifying a long
  (en_US): <longA /></para>

  <para><bold>Spinner</bold> used to edit an element specifying a long 
  (en_US): <longE></longE></para>

  <para><bold>Spinner</bold> used to edit an attribute specifying a
  float (0.0##, fr_FR): <floatA /></para>

  <para><bold>Spinner</bold> used to edit an element specifying a float
  (0.0##, fr_FR): <floatE></floatE></para>

  <para><bold>Spinner</bold> used to edit an attribute specifying a
  double (0.00####, en_US): <doubleA /></para>

  <para><bold>Spinner</bold> used to edit an element specifying a double
  (0.00####, en_US, min=0, max=1, step=0.01): <doubleE></doubleE></para>

  <para>All the following fields allows to use a <bold>date picker</bold> to
  specify a date and/or time, whatever the format used to store this date
  and/or time in the XML document.</para>

  <para>A <bold>date picker</bold> used to edit an attribute specifying a
  date: <date30 /></para>

  <para>A <bold>date picker</bold> used to edit an element specifying a date:
  <date40></date40></para>

  <para>A <bold>date picker</bold> used to edit an attribute specifying a
  time: <time30 /></para>

  <para>A <bold>date picker</bold> used to edit an element specifying a time:
  <time40></time40></para>

  <para>A <bold>date picker</bold> used to edit an attribute specifying a date
  and a time: <dateTime30 /></para>

  <para>A <bold>date picker</bold> used to edit an element specifying a date
  and a time: <dateTime40></dateTime40></para>

  <para>Another <bold>date picker</bold> used to edit an attribute specifying
  a date: <date31 /></para>

  <para>Another <bold>date picker</bold> used to edit an element specifying a
  date: <date41></date41></para>

  <para>Another <bold>date picker</bold> used to edit an attribute specifying
  a time: <time31 /></para>

  <para>Another <bold>date picker</bold> used to edit an element specifying a
  time: <time41></time41></para>

  <para>Another <bold>date picker</bold> used to edit an attribute specifying
  a date and a time: <dateTime31 /></para>

  <para>Another <bold>date picker</bold> used to edit an element specifying a
  date and a time: <dateTime41></dateTime41></para>

  <para>A <bold>date picker</bold> used to edit an attribute specifying a date
  and a time expressed as the number of seconds since the Epoch (January 1,
